version: '3.9'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootPWD
      MYSQL_DATABASE: php101wordpress
      MYSQL_USER: php101admin
      MYSQL_PASSWORD: wp101admin

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "36980:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: php101admin
      WORDPRESS_DB_PASSWORD: wp101admin
      WORDPRESS_DB_NAME: php101wordpress
volumes:
  db_data: {}
  wordpress_data: {}